defaults: &defaults
  # HTTP access mode:
  # 1. closed - Authenticate with HTTP basic
  # 2. open - Don't authenticate with HTTP basic
  http_basic_access_mode: closed
  http_basic_name: preview
  http_basic_password: dev  # Update this in production
  test_user_password: password

  application_name: SitatungaCity
  applications_folder: "/var/Apps"
  gemset_name: roan-park-rails.4.2.x
  ruby_version: ruby-2.2.1
  deploy_user: deploy

  miniumum_version_of_bundler: ">=1.8.2"
  miniumum_version_of_rake: ">=10.4.2"

  # Multi-stage recipe settings
  # Virtual deployment
  virtual_deployment_path: virtual
  virtual_repository_deployment_branch: master
  virtual_server_name: rails.vm
  virtual_stage_name: virtual

  # Staging deployment
  staging_deployment_path: staging
  staging_repository_deployment_branch: master
  staging_server_name: asher.vps
  staging_stage_name: staging

  # Production deployment
  production_deployment_path: production
  production_repository_deployment_branch: master
  production_server_name: gad.vps
  production_stage_name: production

  # Asset vault
  asset_vault_path: /var/AssetsVault

  # Piwik analytics server
  #analytics_server: analytics.dev

  # Reserved numbers
  reserved_phone_numbers:
    airtel:
      "0970000000": "0970000000"
      "0970000001": "0970000001"
      "0970000002": "0970000002"
    mtn:
      "0960000000": "0960000000"
      "0960000001": "0960000001"
      "0960000002": "0960000002"
    zamtel:
      "0950000000": "0950000000"
      "0950000001": "0950000001"
      "0950000002": "0950000002"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

  # HTTP access mode:
  # 1. closed - Authenticate with HTTP basic
  # 2. open - Don't authenticate with HTTP basic
  http_basic_access_mode: open
